### 01 - Teste de gravidez
Escreva uma célula com controle de fluxos que tem como premissa a existência das seguintes variáveis:

- ```sexo``` como ```str``` indicando os valores '**M**' para masculino e '**F**' para feminino  
- ```beta_hcg``` que indica a quantidade do beta-HCG no sangue em mUI/mL.

A sua tarefa é escrever um código que imprima como resultado "indivíduo do sexo masculino" quando sexo = 'M', caso sexo = 'F', se o valor de beta-HCG for maior que 5, retorne "Positivo" indicando que a paciente está grávida, e retorne "Negativo" caso contrário.

Não mexa nos valores da variável ```sexo``` nem em ```beta_hcg```, e escreva um código que funcione para quaisquer valores possíveis de ambos: ```sexo``` = '**M**' ou '**F**' e ```beta_hcg``` assumindo valores inteiros positivos.

In [22]:
sexo = 'M'
beta_hcg = 5

# seu código vem abaixo desta linha

if sexo == 'M':
    print('Indivíduo do sexo masculino')
if sexo == 'F':
    print('indivíduo do sexo feminino')
    
if beta_hcg > 5:
    print('Positivo')
if beta_hcg <= 5:
    print('Negativo')

Indivíduo do sexo masculino
Negativo


### 02 - Renomeando variáveis

Vamos ver adiante que uma forma de renomear variáveis de um conjunto de dados é através de dicionários - o dicionário deve conter como chave o nome original, associando a cada chave um único valor (tipo *str*) que contenha o nome novo.

A sua tarefa é escrever um dicionário que possa ser utilizado para traduzir as variáveis ```name``` (nome), ```age``` (idade) e ```income``` (renda). Ou seja, esse dicionário deve relacionar as chaves *name, age* e *income* às suas respectivas traduções.

In [24]:
dic_renomeacao = {'name':'João', 'age':21 , 'income':10000}
dic_renomeacao

{'name': 'João', 'age': 21, 'income': 10000}

### 03 - É divisível?
A sua tarefa é escrever um código que indique se um número ```N``` é divisível por um número P. Escreva um programa que faça essa verificação para quaisquer combinações de ```N``` e ```M``` e devolva uma mensagem indicativa no output.

In [12]:
N = 42
M = 7

#Seu código
P = []

for i in range(1, N//2+1):
    if N % i == 0:
        P.append(i)

print("Os divisores de", N, "são:", P)

Os divisores de 42 são: [1, 2, 3, 6, 7, 14, 21]


### 04 - Números primos
> Um número **N** é primo se e somente se é divisível por 1, -1, por **N** e por -**N**.  

Escreva um script que verifica se ```N``` é um número primo, verificando se ```N``` é divisível por todos os números de ```1``` a ```N-1```. Você vai precisar usar alguma ferramenta de *loop* que você aprendeu para isto. No final, devolva uma mensagem no output indicando se o número é primo ou não.

In [71]:
N = 47

# seu código abaixo
def is_prime(N):
    if N <= 1:
        return 'N não é um número primo.'
    for i in range(2, int(N**0.5) + 1):
        if N % i == 0:
            return 'N não é um número primo.'
    return 'N é um número primo.'

print(is_prime(N))

N é um número primo.


### 05 - Desafio
O algorítmo do exercício anterior não é o mais eficiente. O que você pode fazer para deixá-lo mais eficiente? Ou seja, executar menos comparações, portanto consumir menos tempo.
1. Será que precisamos correr o loop até o final sempre?
2. Será que precisamos mesmo verificar **todos** os números?
3. Será que precisamos ir até N-1?

Essas perguntas levam ao tipo de pensamento voltado a deixar um algoritmo mais eficiente. Veja se você consegue melhorar o seu.

In [55]:
N = 98

# seu código aqui
def is_prime(num):
    if N <= 1:
        return False
    for i in range(2, int(num**0.5)+1):
        if N % i == 0:
            return False
    return True

divisores_primos = []

for i in range(1, N//2+1):
    if N % i == 0 and is_prime(i):
        divisores_primos.append(i)

divisores_primos.append(N)

print("Os divisores primos de", N, "são:", divisores_primos)


Os divisores primos de 98 são: [1, 2, 98]


### 06 - Peso ideal 1
O IMC (índice de massa corpórea) é um indicador de saúde mais bem aceito que o peso. Ele é calculado como:

$$ IMC = \dfrac{peso}{altura^2}$$

Segundo a OMS, valores *normais* são entre 18.5 e 24.9.

Sua tarefa é encontrar o ponto médio dessa faixa.

In [75]:
imc_ideal = []

lim_min = 18.5
lim_max = 24.9

imc_ideal = (lim_min + lim_max) / 2

print("A média de", lim_min, "e", lim_max, "é", imc_ideal)

A média de 18.5 e 24.9 é 21.7


### 07 - Peso ideal 2
Recebendo um valor de altura, encontre o peso '*ideal*' dessa pessoa, que fornece o IMC encontrado acima

In [82]:
altura = 1.70

# Seu código
peso_ideal = imc_ideal * altura**2
peso_ideal

63.57999999999999

### 08 - Peso ideal 3
Dada uma lista contendo as alturas de pacientes, crie uma nova lista que contenha o peso '*ideal*' (que fornece o IMC calculado em **Peso ideal 1**) desses pacientes.

In [83]:
lista_alturas = [1.95, 2.05, 1.70, 1.65]

lista_peso_ideal = []

# seu código

imc_ideal = 22

for altura in lista_alturas:
    peso_ideal = imc_ideal * altura ** 2
    lista_peso_ideal.append(peso_ideal)

print(lista_peso_ideal)

[83.655, 92.455, 63.57999999999999, 59.894999999999996]


### 09 - Peso ideal 4
Dada uma lista de tuplas - cada elemento da lista é uma tupla contendo altura e peso de um paciente - crie uma nova lista com o IMC desses pacientes.

In [96]:
altura_peso = [(1.80, 90), (1.65, 75), (1.91, 70)]

imc = []

# seu código
for altura, peso in altura_peso:
    valor_imc = peso / (altura ** 2)
    imc.append(valor_imc)
    
    print("IMC list:", imc)

IMC list: [27.777777777777775]
IMC list: [27.777777777777775, 27.548209366391188]
IMC list: [27.777777777777775, 27.548209366391188, 19.188070502453332]


### 10 - Peso ideal 5
Dada uma lista de **listas** - cada elemento da lista é uma **lista** contendo altura e peso de um paciente, adicione mais um elemento à lista de cada paciente contendo o IMC do paciente. Verifique também se é 'baixo', 'normal' ou 'alto' segundo os padrões da OMS em que normal é entre 18.5 e 24.9.

Reflexão: por que no problema anterior temos que criar uma nova lista, e não podemos adicionar os dados de cada indivíduo à tupla?

In [104]:
altura_peso = [[1.80, 90], [1.65, 75], [1.91, 70]]

# seu código

imc_lista = []
categoria_lista = []

for altura, peso in altura_peso:
    imc_value = peso / (altura ** 2)
    imc_lista.append(imc_value)
    
    if valor_imc < 18.5:
        categoria = "Baixo"
    elif valor_imc >= 18.5 and imc_value < 25:
        categoria = "Normal"
    elif valor_imc >= 25 and imc_value < 30:
        categoria = "Alto"
    
    categoria_lista.append(categoria)

altura_peso_imc_cat = []

for i in range(len(altura_peso)):
    altura = altura_peso[i][0]
    peso = altura_peso[i][1]
    imc = imc_list[i]
    categoria = categoria_lista[i]
    altura_peso_imc_cat.append((altura, peso, imc, categoria))

print("altura_peso_imc_cat:", altura_peso_imc_cat)

altura_peso_imc_cat: [(1.8, 90, 27.777777777777775, 'Normal'), (1.65, 75, 27.548209366391188, 'Normal'), (1.91, 70, 19.188070502453332, 'Normal')]
